import { GeographicEntity } from '../../src/types/atlas.js';
import { OFFICIAL_SOURCES } from './seed.data.js';

// Comprehensive Worldwide Geographic Entities
// Covering countries, states/provinces, rivers, mountains, mountain ranges, oceans, seas, and natural wonders.

export const WORLD_ENTITIES: GeographicEntity[] = [
  // =========================================================================
  // 1. WORLD COUNTRIES (Major sovereign states across every continent)
  // =========================================================================
  // Europe
  {
    id: 'italy',
    name: 'Italy',
    nativeName: 'Repubblica Italiana',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [41.8719, 12.5674],
    bbox: [36.6, 6.6, 47.1, 18.5],
    areaKm2: 301340,
    population: 58850000,
    capital: 'Rome',
    description: 'Boot-shaped Southern European peninsula in the central Mediterranean Sea, bordered by the Alps to the north and home to diverse volcanic and agricultural regions.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'spain',
    name: 'Spain',
    nativeName: 'España',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [40.4637, -3.7492],
    bbox: [36.0, -9.3, 43.8, 3.3],
    areaKm2: 505990,
    population: 48000000,
    capital: 'Madrid',
    description: 'Southwestern European nation on the Iberian Peninsula, characterized by the Meseta Central plateau, Pyrenees mountains, and extensive Atlantic and Mediterranean coastlines.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    nativeName: 'Schweiz / Suisse / Svizzera',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [46.8182, 8.2275],
    bbox: [45.8, 5.9, 47.8, 10.5],
    areaKm2: 41285,
    population: 8770000,
    capital: 'Bern',
    description: 'Landlocked Central European alpine country known for the Swiss Alps, high-altitude glaciers, pristine alpine lakes, and headwaters of the Rhine and Rhone rivers.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'norway',
    name: 'Norway',
    nativeName: 'Norge',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [60.4720, 8.4689],
    bbox: [57.9, 4.5, 71.2, 31.1],
    areaKm2: 385207,
    population: 5480000,
    capital: 'Oslo',
    description: 'Nordic country encompassing the western Scandinavian Peninsula with dramatic glaciated fjords, Arctic tundra, and the Scandinavian Mountains.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'sweden',
    name: 'Sweden',
    nativeName: 'Sverige',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [60.1282, 18.6435],
    bbox: [55.3, 11.0, 69.1, 24.2],
    areaKm2: 450295,
    population: 10500000,
    capital: 'Stockholm',
    description: 'Scandinavian country of vast boreal forests, thousands of coastal islands and inland glacial lakes, and the Baltic Sea maritime corridor.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    nativeName: 'Nederland',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [52.1326, 5.2913],
    bbox: [50.7, 3.3, 53.6, 7.2],
    areaKm2: 41850,
    population: 17800000,
    capital: 'Amsterdam',
    description: 'Low-lying Western European nation famous for polders, complex flood control dykes, North Sea coastline, and the Rhine-Meuse-Scheldt delta.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'greece',
    name: 'Greece',
    nativeName: 'Ελλάδα (Elláda)',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [39.0742, 21.8243],
    bbox: [34.8, 19.3, 41.7, 28.3],
    areaKm2: 131957,
    population: 10430000,
    capital: 'Athens',
    description: 'Southeastern European country at the crossroads of Europe, Asia, and Africa, featuring over 2,000 Mediterranean and Aegean islands and rugged limestone ranges.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'russia',
    name: 'Russia',
    nativeName: 'Россия (Rossiya)',
    type: 'country',
    parentId: 'europe',
    parentName: 'Eurasia',
    coordinates: [61.5240, 105.3188],
    bbox: [41.2, 19.6, 81.9, 179.9],
    areaKm2: 17098242,
    population: 144000000,
    capital: 'Moscow',
    description: 'Largest country in the world by surface area, spanning Eastern Europe and Northern Asia across 11 time zones, housing Lake Baikal and the Ural Mountains.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'poland',
    name: 'Poland',
    nativeName: 'Polska',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [51.9194, 19.1451],
    bbox: [49.0, 14.1, 54.8, 24.1],
    areaKm2: 312696,
    population: 38000000,
    capital: 'Warsaw',
    description: 'Central European nation bounded by the Baltic Sea to the north and Carpathian and Sudeten mountains to the south, traversed by the Vistula River.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'ukraine',
    name: 'Ukraine',
    nativeName: 'Україна',
    type: 'country',
    parentId: 'europe',
    parentName: 'Europe',
    coordinates: [48.3794, 31.1656],
    bbox: [44.4, 22.1, 52.4, 40.2],
    areaKm2: 603550,
    population: 38000000,
    capital: 'Kyiv',
    description: 'Eastern European country known for fertile black-soil (chernoziom) agricultural plains, the Dnieper River drainage basin, and Black Sea coastline.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // Asia & Middle East
  {
    id: 'south_korea',
    name: 'South Korea',
    nativeName: '대한민국 (Daehan Minguk)',
    type: 'country',
    parentId: 'asia',
    parentName: 'Asia',
    coordinates: [35.9078, 127.7669],
    bbox: [33.1, 124.6, 38.6, 131.0],
    areaKm2: 100210,
    population: 51740000,
    capital: 'Seoul',
    description: 'East Asian country occupying the southern half of the Korean Peninsula, featuring mountainous terrain along the Taebaek Mountains and intensive coastal plains.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    nativeName: 'Republik Indonesia',
    type: 'country',
    parentId: 'asia',
    parentName: 'Asia / Oceania',
    coordinates: [-0.7893, 113.9213],
    bbox: [-11.0, 95.0, 6.0, 141.0],
    areaKm2: 1904569,
    population: 277500000,
    capital: 'Jakarta (Nusantara)',
    description: 'World\'s largest archipelagic state comprising over 17,000 islands straddling the Equator, located on the Pacific Ring of Fire with rich volcanic biodiversity.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'saudi_arabia',
    name: 'Saudi Arabia',
    nativeName: 'المملكة العربية السعودية',
    type: 'country',
    parentId: 'asia',
    parentName: 'Middle East, Asia',
    coordinates: [23.8859, 45.0792],
    bbox: [16.4, 34.5, 32.2, 55.7],
    areaKm2: 2149690,
    population: 36400000,
    capital: 'Riyadh',
    description: 'Dominant nation on the Arabian Peninsula bounded by the Red Sea and Persian Gulf, home to the vast Rub\' al Khali (Empty Quarter) desert and extensive energy reserves.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'turkey',
    name: 'Turkey (Türkiye)',
    nativeName: 'Türkiye Cumhuriyeti',
    type: 'country',
    parentId: 'asia',
    parentName: 'Eurasia',
    coordinates: [38.9637, 35.2433],
    bbox: [35.8, 25.7, 42.1, 44.8],
    areaKm2: 783562,
    population: 85300000,
    capital: 'Ankara',
    description: 'Transcontinental nation bridging Southeastern Europe and Western Asia across the Bosphorus Strait, characterized by Anatolian plateau, Black Sea, and Mediterranean shores.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'iran',
    name: 'Iran',
    nativeName: 'ایران (Īrān)',
    type: 'country',
    parentId: 'asia',
    parentName: 'Middle East, Asia',
    coordinates: [32.4279, 53.6880],
    bbox: [25.1, 44.0, 39.8, 63.3],
    areaKm2: 1648195,
    population: 88500000,
    capital: 'Tehran',
    description: 'Western Asian nation on the Iranian Plateau framed by the Zagros and Alborz mountain ranges, bordered by the Caspian Sea and Persian Gulf.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    nativeName: 'پاکستان (Pākistān)',
    type: 'country',
    parentId: 'asia',
    parentName: 'South Asia',
    coordinates: [30.3753, 69.3451],
    bbox: [23.7, 60.9, 37.1, 77.8],
    areaKm2: 881913,
    population: 241500000,
    capital: 'Islamabad',
    description: 'South Asian nation spanning from the Arabian Sea coastline to the Karakoram and Hindu Kush peaks (including K2), centered around the fertile Indus River basin.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    nativeName: 'বাংলাদেশ (Bānlādēśa)',
    type: 'country',
    parentId: 'asia',
    parentName: 'South Asia',
    coordinates: [23.6850, 90.3563],
    bbox: [20.7, 88.0, 26.6, 92.7],
    areaKm2: 147570,
    population: 171200000,
    capital: 'Dhaka',
    description: 'South Asian riverine country occupying the fertile Bengal delta, formed by the confluence of the Padma (Ganges), Jamuna (Brahmaputra), and Meghna rivers.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'thailand',
    name: 'Thailand',
    nativeName: 'ประเทศไทย (Prathet Thai)',
    type: 'country',
    parentId: 'asia',
    parentName: 'Southeast Asia',
    coordinates: [15.8700, 100.9925],
    bbox: [5.6, 97.3, 20.5, 105.6],
    areaKm2: 513120,
    population: 71700000,
    capital: 'Bangkok',
    description: 'Southeast Asian country bordered by the Gulf of Thailand and Andaman Sea, encompassing the central Chao Phraya river plains and lush tropical highlands.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    nativeName: 'Việt Nam',
    type: 'country',
    parentId: 'asia',
    parentName: 'Southeast Asia',
    coordinates: [14.0583, 108.2772],
    bbox: [8.5, 102.1, 23.4, 109.5],
    areaKm2: 331212,
    population: 98200000,
    capital: 'Hanoi',
    description: 'S-shaped coastal country on the eastern Indochina Peninsula along the South China Sea, renowned for the Red River delta in the north and Mekong delta in the south.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'philippines',
    name: 'Philippines',
    nativeName: 'Pilipinas',
    type: 'country',
    parentId: 'asia',
    parentName: 'Southeast Asia',
    coordinates: [12.8797, 121.7740],
    bbox: [4.6, 116.9, 21.1, 126.6],
    areaKm2: 300000,
    population: 115600000,
    capital: 'Manila',
    description: 'Archipelagic nation in Southeast Asia situated in the western Pacific Ocean, consisting of 7,641 islands grouped under Luzon, Visayas, and Mindanao.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'nepal',
    name: 'Nepal',
    nativeName: 'नेपाल (Nepāl)',
    type: 'country',
    parentId: 'asia',
    parentName: 'South Asia',
    coordinates: [28.3949, 84.1240],
    bbox: [26.3, 80.0, 30.4, 88.2],
    areaKm2: 147516,
    population: 30500000,
    capital: 'Kathmandu',
    description: 'Landlocked Himalayan nation home to eight of the world\'s ten highest peaks including Mount Everest, descending from alpine glaciers to subtropical Terai plains.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // Americas
  {
    id: 'mexico',
    name: 'Mexico',
    nativeName: 'México',
    type: 'country',
    parentId: 'north_america',
    parentName: 'North America',
    coordinates: [23.6345, -102.5528],
    bbox: [14.5, -118.4, 32.7, -86.7],
    areaKm2: 1964375,
    population: 128500000,
    capital: 'Mexico City',
    description: 'North American nation bordered by the United States, Pacific Ocean, and Gulf of Mexico, with diverse topography of the Sierra Madre ranges and Yucatan Peninsula.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'argentina',
    name: 'Argentina',
    nativeName: 'Argentina',
    type: 'country',
    parentId: 'south_america',
    parentName: 'South America',
    coordinates: [-38.4161, -63.6167],
    bbox: [-55.2, -73.6, -21.8, -53.6],
    areaKm2: 2780400,
    population: 46000000,
    capital: 'Buenos Aires',
    description: 'Second-largest country in South America, spanning the Andes mountains (Aconcagua), the fertile agricultural Pampas, and wind-swept Patagonian glaciers.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'chile',
    name: 'Chile',
    nativeName: 'Chile',
    type: 'country',
    parentId: 'south_america',
    parentName: 'South America',
    coordinates: [-35.6751, -71.5430],
    bbox: [-56.0, -75.6, -17.5, -66.9],
    areaKm2: 756102,
    population: 19600000,
    capital: 'Santiago',
    description: 'Long and narrow country flanking the southwestern edge of South America between the Andes and Pacific Ocean, featuring the arid Atacama Desert and southern fjords.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'colombia',
    name: 'Colombia',
    nativeName: 'Colombia',
    type: 'country',
    parentId: 'south_america',
    parentName: 'South America',
    coordinates: [4.5709, -74.2973],
    bbox: [-4.2, -79.0, 12.5, -66.8],
    areaKm2: 1141748,
    population: 52000000,
    capital: 'Bogotá',
    description: 'Northwestern South American nation with coastlines on both the Pacific and Caribbean, containing three Andean cordilleras, Amazon rainforest, and Los Llanos savannas.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'peru',
    name: 'Peru',
    nativeName: 'Perú',
    type: 'country',
    parentId: 'south_america',
    parentName: 'South America',
    coordinates: [-9.1900, -75.0152],
    bbox: [-18.3, -81.3, -0.03, -68.7],
    areaKm2: 1285216,
    population: 34000000,
    capital: 'Lima',
    description: 'Western South American country facing the Pacific, home to the high Andes cordilleras, Lake Titicaca, the historic Incan citadel of Machu Picchu, and upper Amazon basin.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // Africa & Oceania
  {
    id: 'south_africa',
    name: 'South Africa',
    nativeName: 'Republic of South Africa',
    type: 'country',
    parentId: 'africa',
    parentName: 'Africa',
    coordinates: [-30.5595, 22.9375],
    bbox: [-34.8, 16.5, -22.1, 32.9],
    areaKm2: 1221037,
    population: 60600000,
    capital: 'Pretoria / Cape Town / Bloemfontein',
    description: 'Southernmost country in Africa bordered by both Atlantic and Indian oceans, characterized by the Great Escarpment (Drakensberg) and rich mineral savannas.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    nativeName: 'Federal Republic of Nigeria',
    type: 'country',
    parentId: 'africa',
    parentName: 'West Africa',
    coordinates: [9.0820, 8.6753],
    bbox: [4.3, 2.7, 13.9, 14.7],
    areaKm2: 923768,
    population: 224000000,
    capital: 'Abuja',
    description: 'Most populous nation in Africa on the Gulf of Guinea, traversing ecosystems from mangroves in the Niger Delta to tropical rainforest and northern Sahel savannas.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'kenya',
    name: 'Kenya',
    nativeName: 'Republic of Kenya',
    type: 'country',
    parentId: 'africa',
    parentName: 'East Africa',
    coordinates: [-0.0236, 37.9062],
    bbox: [-4.7, 33.9, 5.0, 41.9],
    areaKm2: 580367,
    population: 55000000,
    capital: 'Nairobi',
    description: 'East African nation straddling the equator along the Indian Ocean, bisected by the Great Rift Valley and home to Mount Kenya and the Maasai Mara ecosystem.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'new_zealand',
    name: 'New Zealand',
    nativeName: 'Aotearoa',
    type: 'country',
    parentId: 'oceania',
    parentName: 'Oceania',
    coordinates: [-40.9006, 174.8860],
    bbox: [-47.3, 166.4, -34.4, 178.6],
    areaKm2: 268021,
    population: 5200000,
    capital: 'Wellington',
    description: 'Island country in the southwestern Pacific Ocean comprising the North and South Islands, featuring active geothermal fields and the glaciated Southern Alps.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // =========================================================================
  // 2. WORLD STATES, PROVINCES & REGIONS
  // =========================================================================
  {
    id: 'texas',
    name: 'Texas',
    nativeName: 'Texas',
    type: 'state',
    parentId: 'usa',
    parentName: 'United States',
    coordinates: [31.9686, -99.9018],
    bbox: [25.8, -106.6, 36.5, -93.5],
    areaKm2: 695662,
    population: 30000000,
    capital: 'Austin',
    description: 'Second-largest US state by area and population, stretching from Gulf Coast subtropical plains and pine forests to arid Chihuahuan Desert mountains.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'new_york_state',
    name: 'New York (State)',
    nativeName: 'New York',
    type: 'state',
    parentId: 'usa',
    parentName: 'United States',
    coordinates: [40.7128, -74.0060],
    bbox: [40.5, -79.8, 45.0, -71.8],
    areaKm2: 141300,
    population: 19600000,
    capital: 'Albany',
    description: 'Mid-Atlantic and Northeastern US state bounded by Lake Ontario, Lake Erie, the Atlantic Ocean, Adirondack Mountains, and the Hudson River valley.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'florida',
    name: 'Florida',
    nativeName: 'Florida',
    type: 'state',
    parentId: 'usa',
    parentName: 'United States',
    coordinates: [27.6648, -81.5158],
    bbox: [24.5, -87.6, 31.0, -80.0],
    areaKm2: 170312,
    population: 22600000,
    capital: 'Tallahassee',
    description: 'Southeastern US peninsula between the Gulf of Mexico and Atlantic Ocean, home to the subtropical Everglades wetlands and coral reefs of the Florida Keys.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'alaska',
    name: 'Alaska',
    nativeName: 'Alaska',
    type: 'state',
    parentId: 'usa',
    parentName: 'United States',
    coordinates: [64.2008, -149.4937],
    bbox: [51.2, -179.1, 71.4, -130.0],
    areaKm2: 1723337,
    population: 733000,
    capital: 'Juneau',
    description: 'Largest US state by area situated in northwest North America, dominated by glaciated mountain ranges, volcanic Aleutian islands, Arctic tundra, and Mount Denali.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'hawaii',
    name: 'Hawaii',
    nativeName: 'Mokuʻāina o Hawaiʻi',
    type: 'state',
    parentId: 'usa',
    parentName: 'United States',
    coordinates: [19.8968, -155.5828],
    bbox: [18.9, -160.2, 22.2, -154.8],
    areaKm2: 28311,
    population: 1440000,
    capital: 'Honolulu',
    description: 'Volcanic island archipelago in the central Pacific Ocean, featuring active shield volcanoes (Mauna Loa, Kilauea), tropical rainforests, and coral reefs.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'ontario',
    name: 'Ontario',
    nativeName: 'Ontario',
    type: 'province',
    parentId: 'canada',
    parentName: 'Canada',
    coordinates: [51.2538, -85.3232],
    bbox: [41.7, -95.2, 56.9, -74.3],
    areaKm2: 1076395,
    population: 15500000,
    capital: 'Toronto',
    description: 'Most populous Canadian province, bordering the Great Lakes and Hudson Bay, containing the Niagara Escarpment and mineral-rich Canadian Shield.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'british_columbia',
    name: 'British Columbia',
    nativeName: 'British Columbia',
    type: 'province',
    parentId: 'canada',
    parentName: 'Canada',
    coordinates: [53.7267, -127.6476],
    bbox: [48.3, -139.1, 60.0, -114.0],
    areaKm2: 944735,
    population: 5400000,
    capital: 'Victoria',
    description: 'Westernmost Canadian province between the Pacific Ocean and the Rocky Mountains, covered by temperate rainforests, deep fjords, and glacier peaks.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'bavaria',
    name: 'Bavaria',
    nativeName: 'Bayern (Freistaat Bayern)',
    type: 'state',
    parentId: 'germany',
    parentName: 'Germany',
    coordinates: [48.7904, 11.4979],
    bbox: [47.3, 8.9, 50.6, 13.8],
    areaKm2: 70550,
    population: 13300000,
    capital: 'Munich',
    description: 'Southern German state characterized by the Bavarian Alps, Bavarian Forest, the Danube River valley, and scenic alpine foothills.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'queensland',
    name: 'Queensland',
    nativeName: 'Queensland',
    type: 'state',
    parentId: 'australia',
    parentName: 'Australia',
    coordinates: [-20.9176, 142.7028],
    bbox: [-29.2, 138.0, -10.7, 153.6],
    areaKm2: 1852642,
    population: 5400000,
    capital: 'Brisbane',
    description: 'Northeastern Australian state home to the Great Barrier Reef, tropical Daintree rainforest, Cape York Peninsula, and arid outback channel country.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'tokyo_prefecture',
    name: 'Tokyo Metropolis',
    nativeName: '東京都 (Tōkyō-to)',
    type: 'state',
    parentId: 'japan',
    parentName: 'Japan',
    coordinates: [35.6762, 139.6503],
    bbox: [35.5, 138.9, 35.9, 139.9],
    areaKm2: 2194,
    population: 14100000,
    capital: 'Shinjuku',
    description: 'Capital region and most populous prefecture of Japan, located on the head of Tokyo Bay in the Kanto plain, encompassing urban and Izu island territories.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // =========================================================================
  // 3. WORLD RIVERS (Major planetary river systems)
  // =========================================================================
  {
    id: 'mississippi_river',
    name: 'Mississippi River',
    nativeName: 'Mississippi River',
    type: 'river',
    parentId: 'usa',
    parentName: 'North America',
    coordinates: [32.0, -91.0],
    areaKm2: 3220000, // drainage basin
    description: 'Chief river of the largest drainage system on the North American continent, flowing 3,766 km from Lake Itasca in Minnesota south to the Gulf of Mexico.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'yangtze_river',
    name: 'Yangtze River (Chang Jiang)',
    nativeName: '长江 (Cháng Jiāng)',
    type: 'river',
    parentId: 'china',
    parentName: 'China, Asia',
    coordinates: [31.2304, 115.0],
    areaKm2: 1808500,
    description: 'Longest river in Eurasia and third-longest in the world (6,300 km), originating in the Tibetan Plateau and flowing through the Three Gorges into the East China Sea.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'danube_river',
    name: 'Danube River',
    nativeName: 'Donau / Dunav / Duna',
    type: 'river',
    parentId: 'europe',
    parentName: 'Central & Eastern Europe',
    coordinates: [45.2, 29.5],
    areaKm2: 801463,
    description: 'Second-longest river in Europe (2,850 km), rising in the Black Forest of Germany and flowing through 10 countries before emptying into the Black Sea via the Danube Delta.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'ganges_river',
    name: 'Ganges River (Ganga)',
    nativeName: 'गंगा (Gangā)',
    type: 'river',
    parentId: 'india',
    parentName: 'India & Bangladesh, Asia',
    coordinates: [25.3, 83.0],
    areaKm2: 1080000,
    description: 'Trans-boundary river of Asia rising in the western Himalayas (Gangotri Glacier) and flowing 2,525 km across the Indo-Gangetic Plain into the Bay of Bengal.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.SURVEY_OF_INDIA,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'rhine_river',
    name: 'Rhine River',
    nativeName: 'Rhein / Rhin / Rijn',
    type: 'river',
    parentId: 'europe',
    parentName: 'Western Europe',
    coordinates: [50.0, 7.5],
    areaKm2: 185000,
    description: 'Major European river (1,230 km) originating in the Swiss Alps, serving as the historical industrial and commercial waterway connecting Switzerland, Germany, France, and the Netherlands.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'volga_river',
    name: 'Volga River',
    nativeName: 'Волга',
    type: 'river',
    parentId: 'russia',
    parentName: 'European Russia',
    coordinates: [48.7, 44.5],
    areaKm2: 1360000,
    description: 'Longest river in Europe (3,531 km) with the largest discharge and drainage basin, flowing through central Russia into the landlocked Caspian Sea.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'thames_river',
    name: 'River Thames',
    nativeName: 'River Thames',
    type: 'river',
    parentId: 'uk',
    parentName: 'England, United Kingdom',
    coordinates: [51.5, 0.0],
    areaKm2: 12935,
    description: 'Historic river flowing 346 km through southern England and central London into the North Sea, vital for English maritime trade, navigation, and geography.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mekong_river',
    name: 'Mekong River',
    nativeName: 'Mê Kông / แม่น้ำโขง / 澜沧江 (Láncāng Jiāng)',
    type: 'river',
    parentId: 'asia',
    parentName: 'Southeast Asia',
    coordinates: [10.5, 106.0],
    areaKm2: 795000,
    description: 'Trans-boundary river in Southeast Asia (4,909 km) flowing from the Tibetan Plateau through China, Myanmar, Laos, Thailand, Cambodia, and Vietnam into the South China Sea.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'congo_river',
    name: 'Congo River',
    nativeName: 'Fleuve Congo',
    type: 'river',
    parentId: 'africa',
    parentName: 'Central Africa',
    coordinates: [-4.3, 15.3],
    areaKm2: 4014500,
    description: 'Second-longest river in Africa (4,700 km) and the world\'s deepest recorded river (over 220 m deep), discharging second only to the Amazon through the Congo rainforest.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'colorado_river',
    name: 'Colorado River',
    nativeName: 'Colorado River',
    type: 'river',
    parentId: 'usa',
    parentName: 'Southwestern North America',
    coordinates: [36.0, -114.0],
    areaKm2: 640000,
    description: 'Principal river of the Southwestern US and northwestern Mexico (2,330 km), renowned for carving the Grand Canyon and supplying vital desert irrigation and hydroelectric power.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'indus_river',
    name: 'Indus River',
    nativeName: 'دریائے سندھ / सिन्धु नदी',
    type: 'river',
    parentId: 'pakistan',
    parentName: 'South Asia',
    coordinates: [28.0, 69.5],
    areaKm2: 1165000,
    description: 'Major trans-Himalayan river of South and Central Asia (3,180 km), giving its name to India and nurturing ancient civilizations as Pakistan\'s agricultural backbone.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'yellow_river',
    name: 'Yellow River (Huang He)',
    nativeName: '黄河 (Huáng Hé)',
    type: 'river',
    parentId: 'china',
    parentName: 'China, Asia',
    coordinates: [37.8, 118.8],
    areaKm2: 752443,
    description: 'Second-longest river in China (5,464 km), celebrated as the "Cradle of Chinese Civilization" for its fertile loess sediment and historical delta shifts into the Bohai Sea.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // =========================================================================
  // 4. WORLD MOUNTAINS, VOLCANOES & MOUNTAIN RANGES
  // =========================================================================
  {
    id: 'k2_peak',
    name: 'K2 (Mount Godwin-Austen / Chhogori)',
    nativeName: 'کے ٹو (K2) / ཆོག་གྷོ་རི',
    type: 'mountain',
    parentId: 'pakistan',
    parentName: 'Karakoram Range, Asia',
    coordinates: [35.8814, 76.5133],
    elevationM: 8611,
    description: 'Second-highest mountain on Earth (8,611 m) on the Pakistan-China border in the Karakoram, famed as the "Savage Mountain" for extreme climbing difficulty.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mount_kilimanjaro',
    name: 'Mount Kilimanjaro',
    nativeName: 'Kilimanjaro',
    type: 'volcano',
    parentId: 'africa',
    parentName: 'Tanzania, Africa',
    coordinates: [-3.0674, 37.3556],
    elevationM: 5895,
    description: 'Dormant stratovolcano in Tanzania and the highest mountain in Africa (5,895 m), rising majestically above the African savanna with equatorial ice caps.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mont_blanc',
    name: 'Mont Blanc (Monte Bianco)',
    nativeName: 'Mont Blanc / Monte Bianco',
    type: 'mountain',
    parentId: 'europe',
    parentName: 'Graian Alps, France/Italy',
    coordinates: [45.8326, 6.8652],
    elevationM: 4809,
    description: 'Highest mountain in the Alps and Western Europe (4,809 m), capped by a permanent dome of snow and ice along the French-Italian alpine frontier.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'matterhorn',
    name: 'Matterhorn (Cervino)',
    nativeName: 'Matterhorn / Monte Cervino',
    type: 'mountain',
    parentId: 'europe',
    parentName: 'Pennine Alps, Switzerland/Italy',
    coordinates: [45.9763, 7.6586],
    elevationM: 4478,
    description: 'Iconic pyramidal peak of the Alps (4,478 m) straddling the Swiss-Italian border, famous for its nearly symmetrical four steep triangular faces pointing toward the compass points.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mount_denali',
    name: 'Mount Denali (Mount McKinley)',
    nativeName: 'Denali',
    type: 'mountain',
    parentId: 'alaska',
    parentName: 'Alaska Range, United States',
    coordinates: [63.0692, -151.0070],
    elevationM: 6190,
    description: 'Highest mountain peak in North America (6,190 m above sea level), possessing the third most prominent and isolated peak in the world with severe subarctic climate.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'aconcagua',
    name: 'Aconcagua',
    nativeName: 'Aconcagua',
    type: 'mountain',
    parentId: 'argentina',
    parentName: 'Principal Cordillera, Andes, Argentina',
    coordinates: [-32.6532, -70.0109],
    elevationM: 6961,
    description: 'Highest mountain in the Americas and the highest outside Asia (6,961 m), crowning the Andes in Mendoza Province, Argentina.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mount_elbrus',
    name: 'Mount Elbrus',
    nativeName: 'Эльбрус (Elbrus) / Минги Тау',
    type: 'volcano',
    parentId: 'russia',
    parentName: 'Caucasus Mountains, Russia',
    coordinates: [43.3499, 42.4453],
    elevationM: 5642,
    description: 'Dormant stratovolcano in the Caucasus Mountains and the highest peak in Europe (5,642 m), capped with 22 glaciers feeding regional rivers.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mount_vesuvius',
    name: 'Mount Vesuvius',
    nativeName: 'Monte Vesuvio',
    type: 'volcano',
    parentId: 'italy',
    parentName: 'Campania, Italy',
    coordinates: [40.8214, 14.4260],
    elevationM: 1281,
    description: 'Somma-stratovolcano on the Gulf of Naples, famous for its AD 79 catastrophic eruption that buried the Roman cities of Pompeii and Herculaneum.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mount_rainier',
    name: 'Mount Rainier (Tahoma)',
    nativeName: 'Tahoma / Mount Rainier',
    type: 'volcano',
    parentId: 'usa',
    parentName: 'Cascade Range, Washington, USA',
    coordinates: [46.8523, -121.7603],
    elevationM: 4392,
    description: 'Large active stratovolcano in Washington state, the most topographically prominent mountain in the contiguous United States, spawning 26 major glaciers.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'himalayas_range',
    name: 'Himalayas Mountain Range',
    nativeName: 'हिमालय (Himālaya - Abode of Snow)',
    type: 'mountain_range',
    parentId: 'asia',
    parentName: 'South & Central Asia',
    coordinates: [28.0, 84.0],
    elevationM: 8848,
    description: 'Vast mountain range in Asia separating the plains of the Indian subcontinent from the Tibetan Plateau, containing over 50 mountains exceeding 7,200 m including Mount Everest.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'rocky_mountains',
    name: 'Rocky Mountains',
    nativeName: 'Rocky Mountains',
    type: 'mountain_range',
    parentId: 'north_america',
    parentName: 'Western North America',
    coordinates: [44.0, -110.0],
    elevationM: 4401,
    description: 'Major mountain range spanning 4,800 km from western Canada to New Mexico, forming the Continental Divide between Pacific and Atlantic drainages.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'alps_range',
    name: 'Alps Mountain Range',
    nativeName: 'Alpen / Alpes / Alpi',
    type: 'mountain_range',
    parentId: 'europe',
    parentName: 'Central & Southern Europe',
    coordinates: [46.5, 9.5],
    elevationM: 4809,
    description: 'Highest and most extensive mountain range system entirely in Europe, stretching 1,200 km across eight alpine countries (France, Switzerland, Monaco, Italy, Liechtenstein, Austria, Germany, and Slovenia).',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'andes_range',
    name: 'Andes Mountain Range',
    nativeName: 'Cordillera de los Andes',
    type: 'mountain_range',
    parentId: 'south_america',
    parentName: 'Western South America',
    coordinates: [-22.0, -68.0],
    elevationM: 6961,
    description: 'Longest continental mountain range in the world (8,900 km), running along the western coast of South America through 7 countries.',
    geometryType: 'LineString',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },

  // =========================================================================
  // 5. NATURAL WONDERS, LAKES, SEAS & OCEANS
  // =========================================================================
  {
    id: 'grand_canyon',
    name: 'Grand Canyon',
    nativeName: 'Grand Canyon',
    type: 'valley',
    parentId: 'usa',
    parentName: 'Arizona, United States',
    coordinates: [36.1069, -112.1129],
    areaKm2: 4926,
    description: 'Steep-sided canyon carved by the Colorado River in Arizona, 446 km long, up to 29 km wide and over 1,857 meters deep, revealing nearly 2 billion years of Earth\'s geological history.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'victoria_falls',
    name: 'Victoria Falls (Mosi-oa-Tunya)',
    nativeName: 'Mosi-oa-Tunya (The Smoke That Thunders)',
    type: 'wetland',
    parentId: 'africa',
    parentName: 'Zambia / Zimbabwe border',
    coordinates: [-17.9243, 25.8572],
    areaKm2: 66,
    description: 'Spectacular waterfall on the Zambezi River between Zambia and Zimbabwe, forming the largest sheet of falling water in the world (1,708 m wide and 108 m high).',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.UNESCO,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'lake_baikal',
    name: 'Lake Baikal',
    nativeName: 'Озеро Байкал (Ozero Baykal)',
    type: 'lake',
    parentId: 'russia',
    parentName: 'Siberia, Russia',
    coordinates: [53.5587, 108.1650],
    areaKm2: 31722,
    description: 'World\'s oldest (25–30 million years) and deepest lake (1,642 m), containing 22–23% of the world\'s fresh surface water—more than all North American Great Lakes combined.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.UNESCO,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'lake_superior',
    name: 'Lake Superior',
    nativeName: 'Lake Superior / Gichigami',
    type: 'lake',
    parentId: 'north_america',
    parentName: 'Canada / United States',
    coordinates: [47.7, -87.5],
    areaKm2: 82103,
    description: 'Largest freshwater lake in the world by surface area, shared by the United States and Canada, forming the head of the Great Lakes-St. Lawrence system.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'pacific_ocean',
    name: 'Pacific Ocean',
    nativeName: 'Pacific Ocean',
    type: 'ocean',
    coordinates: [0.0, -160.0],
    areaKm2: 165250000,
    description: 'Largest and deepest of Earth\'s oceanic divisions, extending from the Arctic in the north to the Southern Ocean, covering roughly 32% of Earth\'s total surface area.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'atlantic_ocean',
    name: 'Atlantic Ocean',
    nativeName: 'Atlantic Ocean',
    type: 'ocean',
    coordinates: [0.0, -25.0],
    areaKm2: 106460000,
    description: 'Second-largest ocean in the world, separating the "Old World" of Europe and Africa from the "New World" of the Americas, with the Mid-Atlantic Ridge seafloor spreading.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'indian_ocean',
    name: 'Indian Ocean',
    nativeName: 'Indian Ocean',
    type: 'ocean',
    coordinates: [-20.0, 80.0],
    areaKm2: 70560000,
    description: 'Third-largest ocean in the world, bounded by Asia to the north, Africa to the west, Australia to the east, and Southern Ocean to the south, driving the monsoon climate system.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mediterranean_sea',
    name: 'Mediterranean Sea',
    nativeName: 'Mare Nostrum / Mer Méditerranée',
    type: 'sea',
    parentId: 'europe',
    parentName: 'Europe, Africa & Asia',
    coordinates: [35.0, 18.0],
    areaKm2: 2500000,
    description: 'Intercontinental sea connected to the Atlantic Ocean through the Strait of Gibraltar, almost completely enclosed by Southern Europe, Northern Africa, and Western Asia.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'dead_sea',
    name: 'Dead Sea (Salt Sea)',
    nativeName: 'ים המלח (Yam HaMélakh) / البحر الميت',
    type: 'lake',
    parentId: 'asia',
    parentName: 'Jordan / Israel border',
    coordinates: [31.5590, 35.4732],
    areaKm2: 605,
    description: 'Landlocked hypersaline lake located in the Jordan Rift Valley, whose shores and surface are 430.5 meters below sea level, Earth\'s lowest land elevation.',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  },
  {
    id: 'mariana_trench',
    name: 'Mariana Trench (Challenger Deep)',
    nativeName: 'Mariana Trench',
    type: 'ocean',
    parentId: 'pacific_ocean',
    parentName: 'Western Pacific Ocean',
    coordinates: [11.3493, 142.1996],
    elevationM: -10994,
    description: 'Deepest oceanic trench on Earth located in the western Pacific Ocean near the Mariana Islands, reaching maximum depth at Challenger Deep (approx. 10,994 meters).',
    geometryType: 'Point',
    sources: OFFICIAL_SOURCES.USGS,
    updatedAt: '2025-01-01T00:00:00Z'
  }
];
